In [6]:
import tensorflow_hub as hub
import tensorflow_text as text

In [7]:
encoder_url="https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"
preprocess_url="https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"

In [8]:
bert_preprocess_model=hub.KerasLayer(preprocess_url)
bert_encoder_model=hub.KerasLayer(encoder_url)

In [15]:
text=["film très intéressant","j'aime programmer"]
preprocess_text_layer=bert_preprocess_model(text)

In [16]:
preprocess_text.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

CLS film très intéressant SEP

In [13]:
preprocess_text['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [17]:
preprocess_text['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  2143, 24403,  6970,  7971,  4630,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [18]:
bert_result=bert_encoder_model(preprocess_text)

In [20]:
bert_result.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [21]:
bert_result['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.87463164, -0.38243318, -0.26445866, ...,  0.0185239 ,
        -0.56862926,  0.85448015],
       [-0.7514066 , -0.36355808, -0.55052906, ..., -0.21925804,
        -0.593769  ,  0.8405341 ]], dtype=float32)>

In [22]:
bert_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 4.7587544e-02,  1.6923460e-01,  7.7126376e-02, ...,
         -2.8983000e-01,  2.2872372e-01,  3.4485805e-01],
        [ 7.6220340e-01,  7.3382723e-01,  1.6153494e-01, ...,
         -3.9449143e-01,  4.9098676e-01, -3.0124626e-01],
        [ 3.6379176e-01, -4.1628414e-01, -3.7541878e-01, ...,
         -2.9409811e-01,  2.2002225e-01,  2.0828578e-01],
        ...,
        [ 2.2621526e-01,  2.7320665e-01,  2.6172823e-01, ...,
         -1.9815063e-01,  1.6402285e-01,  2.8825986e-01],
        [ 1.4901665e-01,  2.5003564e-01,  2.4210921e-01, ...,
         -1.9440858e-01,  1.6394076e-01,  3.0253309e-01],
        [ 1.6990070e-01,  8.7593496e-02,  2.4376702e-01, ...,
         -1.7580509e-01,  1.3445561e-01,  2.5496206e-01]],

       [[-5.8119297e-01,  8.1721887e-02, -2.9347783e-01, ...,
         -2.8365567e-01,  3.3412915e-01,  3.4376150e-01],
        [-5.3166848e-01,  3.4034321e-01,  6.9151513e-02, ...,
          4.5979656e-03, -1.

In [24]:
len(bert_result['encoder_outputs'])

12

In [25]:
bert_result['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.16622841,  0.03289875, -0.07711431, ...,  0.04275141,
          0.07255197,  0.02728849],
        [ 0.5899281 ,  0.59393984, -1.309612  , ...,  0.8691439 ,
          1.4146658 , -0.96069556],
        [ 1.3714678 , -0.63622   , -0.07393055, ..., -0.7915001 ,
          0.7203641 ,  0.67828983],
        ...,
        [-0.0969221 , -0.195195  ,  0.33102673, ...,  0.44727468,
         -0.25405547,  0.1692087 ],
        [-0.19975469, -0.21937357,  0.2046286 , ...,  0.481112  ,
         -0.14943115,  0.0562241 ],
        [-0.04454441, -0.13431303,  0.25578135, ...,  0.8170619 ,
         -0.5051978 , -0.02384561]],

       [[ 0.09130879,  0.13969925, -0.08473843, ...,  0.05927008,
          0.09288895, -0.03891189],
        [ 0.39029324, -0.25342304, -0.2964155 , ...,  0.01349854,
          1.3532654 , -0.5219386 ],
        [-0.6265203 , -0.04400027,  0.46066177, ..., -0.26632017,
          0.6052178 , -1.6482806 ],
        ...,

In [27]:
bert_result['encoder_outputs'][-1]==bert_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>